### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [rozheash/rozheash.github.io#1]
Добрый день. Благодарю за проделанную работу.
К сожалению, текущая версия содержит ряд недостатков, не позволяющих мне засчитать ее на данной итерации:

Регулярные выражения:

Имя
**Нужно исправить** валидацию проходит следующее некорректное имя
Денис- (дефис на конце)
Допустимы только Денис или Денис-Иван.

Email
**Нужно исправить** валидацию не проходит следующий корректный адрес сайта
some-extra-long-name@some.extra.long.domain.name - количество поддоменов в доменном имени может быть произвольным

**Нужно исправить** валидацию проходят следующие некорректные адреса почты
2@-------.ru - доменное имя не может состоять только из спецсимволов, а также начинаться и заканчиваться на них (так же как и имя пользователя)

**Можно лучше** валидацию проходит следующий некорректный кейс
my---mail@site.ru - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным

Номер телефона

Негативные:
**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.

+7(925 900-90-90
+7925900-90-90
+792590090-90
+7-925-900-90-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

Адрес сайта:
**Нужно исправить** валидацию не проходят следующие корректные адреса сайта:
http://some.test.yandex.ru - адрес сайта может содержать в себе произвольное число поддоменов

**Можно лучше** валидацию проходят следующие некорректные адреса сайтов:
http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными. 
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1.

Если какие-то из моих комментарием требуют разъяснений не стесняйтесь задавать вопросы - можете сделать это прямо здесь, обязательно упомянув меня по нику так @zlocate

**Comment by zlocate** [comment]
Добрый день.
К сожалению, кейсы отмеченные ранее, до сих пор не исправлены в версии, размещенной на Github Pages.
Скриншот с примерами кейсов по основным группам:
http://i.imgur.com/ASg8YSo.png

**Comment by zlocate** [comment]
Убедитесь, пожалуйста, что все ваши изменения попали в репозиторий.
Если какие-то из моих комментариев были вам непонятные - не стесняйтесь задавать вопросы.

**Comment by rozheash** [comment]
@zlocate 
Добрый день
Да, что-то пошло не так с загрузкой. Сейчас все обновил. Посмотрите еще раз, пожалуйста

**Comment by zlocate** [comment]
Добрый день. Ничего страшного, главное теперь все правки долетели :)

Осталось 2 кейса, требующих исправления:
Регулярные выражения:
Имя:
**Нужно исправить** Валидацию проходят следующие некорректные адреса
ЁлкаЁлка - в каждой части из имени может быть только одна заглавная буква

Email:
**Нужно исправить** валидацию не проходит следующий корректный адрес сайта:
denis_zlocate@gmail.academy - в имени пользователя (до @ может встречаться символ _ но не более 1го подряд и н не на первой и последней позиции. Т.е _@some.ru ,  _some\_@some.ru, some__@some.ru являются некорректными)

**Comment by zlocate** [comment]
Добрый день. Работа принята.
Желаю вам успехов в дальнейшем прохождении курса.
